services:
  ros2:
    container_name: ps-oce-robot
    image: ghcr.io/rjbaw/octa_ros:latest
    shm_size: '512m'
    environment:
      DISPLAY: ${DISPLAY}
      QT_GRAPHICSSYSTEM: native
      QT_X11_NO_MITSHIM: '1'
      XAUTHORITY: /workspace/.Xauthority
      ROBOT_IP: ${ROBOT_IP:-192.168.56.101}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ${HOME}/.Xauthority:/workspace/.Xauthority:ro
      - ${HOME}:/workspace/home/
      - ${PWD}:/workspace/app/
    user: "${UID}:${GID}"
    devices:
      - /dev/dri:/dev/dri
      - /dev/accel:/dev/accel
    group_add:
      - 105
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
    ulimits:
      rtprio: 99
      nice: -20
      memlock: -1
      core: 0
    command: ["bash"]
    stdin_open: true
    restart: always
    network_mode: host
    privileged: true
    tty: true
