services:
  ros2:
    container_name: ps-oce-robot
    build: .
    shm_size: '512m'
    environment:
      - DISPLAY=$DISPLAY
      - QT_GRAPHICSSYSTEM=native
      - QT_X11_NO_MITSHIM=1
    volumes:
      - $HOME/:/workspace/home/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:ro
      #- $HOME/PS-OCTA-OCE-Robot:/workspace/ps-oce-robot/ # debugging
    restart: always
    network_mode: host
    privileged: true
    tty: true
