services:
  ros2:
    container_name: ps-oce-robot-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    shm_size: '512m'
    environment:
      DISPLAY: ${DISPLAY}
      QT_GRAPHICSSYSTEM: native
      QT_X11_NO_MITSHIM: '1'
      XAUTHORITY: /workspace/.Xauthority
      ROBOT_IP: ${ROBOT_IP:-192.168.56.101}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ${HOME}/.Xauthority:/workspace/.Xauthority:ro
      - ${HOME}:/workspace/home/
      #- $HOME/PS-OCTA-OCE-Robot:/workspace/ps-oce-robot/ # debugging
    restart: always
    network_mode: host
    privileged: true
    tty: true
