services:
  ros2:
    container_name: ps-oce-robot
    image: ghcr.io/rjbaw/octa_ros:latest
    shm_size: '512m'
    environment:
      DISPLAY: ${DISPLAY}
      QT_GRAPHICSSYSTEM: native
      QT_X11_NO_MITSHIM: '1'
      XAUTHORITY: /workspace/.Xauthority
      RCUTILS_LOGGING_DIRECTORY: /workspace/app/logs
      ROBOT_IP: ${ROBOT_IP:-192.168.0.10}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ${HOME}/.Xauthority:/workspace/.Xauthority:ro
      - ${PWD}/logs:/workspace/app/logs
      - ${PWD}/result:/workspace/app/result
    user: "${HOST_UID}:${HOST_GID}"
    devices:
      - /dev/dri:/dev/dri
      - /dev/accel:/dev/accel
    group_add:
      - 105
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
    ulimits:
      rtprio: 99
      nice: -20
      memlock: -1
      core: 0
    restart: always
    network_mode: host
    privileged: true
    tty: true
